@startuml
package "Tezos" {
  NODE_HTTP - [Blockchain node]
  database "Blockchain" {
    frame "Smart contracts" {
       [Marketplace contract]
       [Whitelist contract]
       [Permit contract]
       [NFT contract]
    }
  }
  node "Tezos public infrastructure" {
    TZKT_HTTP - [TZKT Indexer]
    [TZKT Indexer] - TZKT_WS

  }
}



cloud "Application Cloud" {
  [Fractible frontend]
  [Fractible indexer (DipDup)]
  [Fractible backend]
}

cloud "HSM Cloud" {
  PKCS11 - [HSM]
}



[Fractible backend] --> PKCS11
[Fractible frontend] --> [Fractible backend]
[Fractible backend] --> NODE_HTTP
[Fractible backend] --> [Fractible indexer (DipDup)]

[Fractible indexer (DipDup)] --> TZKT_HTTP
[Fractible indexer (DipDup)] --> TZKT_WS
[Blockchain node] --> Blockchain
@enduml