@startuml
package "Tezos" {
  [Wallet]
  [Blockchain node] - NODE_HTTP
  database "Blockchain" {
    frame "Smart contracts" {
       [Marketplace contract]
       [Whitelist contract]
       [Permit contract]
       [NFT contract]
    }
  }
  node "Tezos public infrastructure" {
    TZKT_HTTP - [TZKT Indexer]
    [TZKT Indexer] - TZKT_WS

  }
}



cloud "Application Cloud" {
  [Fractible frontend]
  [Fractible indexer (DipDup)]
  [Fractible backend]
}

cloud "HSM Cloud" {
  PKCS11 - [HSM]
}



[Fractible backend] --> PKCS11
[Fractible frontend] --> [Fractible backend]
[Fractible backend] --> [TZKT Indexer]
[Fractible backend] --> [Blockchain node]
[Fractible backend] --> [Fractible indexer (DipDup)]
[Fractible frontend] --> [Wallet]
[TZKT Indexer] --> [Blockchain node]
[Wallet] --> [Blockchain node]
[Fractible indexer (DipDup)] --> [TZKT Indexer]
[Blockchain node] --> Blockchain
@enduml